



g1=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/mergeVcfGroupwise/AA/AA_TruseqNano_HGCTCDSXY.vcf.gz
g2=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/mergeVcfGroupwise/AM/AM_TruseqNano_HGCTCDSXY.vcf.gz

bedtools jaccard -a $g1 -b  $g2

intersection	union	jaccard	n_intersections
37682193	85068747	0.442962	22550592

bedtools jaccard -a AA_TruseqNano_HGCTCDSXY.vcf.gz -b  PA_TruseqNano_HGCTCDSXY.vcf.gz

intersection	union	jaccard	n_intersections
33200378	88216836	0.37635	20304442

bedtools jaccard -a AA_TruseqNano_HGCTCDSXY.vcf.gz -b  PM_TruseqNano_HGCTCDSXY.vcf.gz

intersection	union	jaccard	n_intersections
35299142	90407022	0.390447	21406139


bedtools jaccard -a AA_TruseqNano_HGCTCDSXY.vcf.gz -b  W_TruseqNano_HGCTCDSXY.vcf.gz

intersection	union	jaccard	n_intersections
34059959	90181908	0.377681	20758143



bcftools isec -p dir AA_TruseqNano_HGCTCDSXY.vcf.gz AM_TruseqNano_HGCTCDSXY.vcf.gz
bcftools index -s 0000.vcf
bcftools stats 0000.vcf

tabix -p vcf AA_TruseqNano_HGCTCDSXY.vcf.gz
tabix -p vcf AM_TruseqNano_HGCTCDSXY.vcf.gz
tabix -p vcf PA_TruseqNano_HGCTCDSXY.vcf.gz
tabix -p vcf PM_TruseqNano_HGCTCDSXY.vcf.gz
tabix -p vcf W_TruseqNano_HGCTCDSXY.vcf.gz

vcf-compare $g1 $g2


vcf-compare AA_TruseqNano_HGCTCDSXY.vcf.gz AM_TruseqNano_HGCTCDSXY.vcf.gz

# This file was generated by vcf-compare.
# The command line was: vcf-compare(v0.1.14-12-gcdb80b8) AA_TruseqNano_HGCTCDSXY.vcf.gz AM_TruseqNano_HGCTCDSXY.vcf.gz
#
#VN 'Venn-Diagram Numbers'. Use `grep ^VN | cut -f 2-` to extract this part.
#VN The columns are:
#VN        1  .. number of sites unique to this particular combination of files
#VN        2- .. combination of files and space-separated number, a fraction of sites in the file
VN	12385438	AA_TruseqNano_HGCTCDSXY.vcf.gz (33.1%)
VN	15341141	AM_TruseqNano_HGCTCDSXY.vcf.gz (38.0%)
VN	25071309	AA_TruseqNano_HGCTCDSXY.vcf.gz (66.9%)	AM_TruseqNano_HGCTCDSXY.vcf.gz (62.0%)
#SN Summary Numbers. Use `grep ^SN | cut -f 2-` to extract this part.
SN	Number of REF matches:	24817551
SN	Number of ALT matches:	23673317
SN	Number of REF mismatches:	253758
SN	Number of ALT mismatches:	1144234
SN	Number of samples in GT comparison:	0


vcf-compare AA_TruseqNano_HGCTCDSXY.vcf.gz PA_TruseqNano_HGCTCDSXY.vcf.gz


# This file was generated by vcf-compare.
# The command line was: vcf-compare(v0.1.14-12-gcdb80b8) AA_TruseqNano_HGCTCDSXY.vcf.gz PA_TruseqNano_HGCTCDSXY.vcf.gz
#
#VN 'Venn-Diagram Numbers'. Use `grep ^VN | cut -f 2-` to extract this part.
#VN The columns are:
#VN        1  .. number of sites unique to this particular combination of files
#VN        2- .. combination of files and space-separated number, a fraction of sites in the file
VN	15236841	AA_TruseqNano_HGCTCDSXY.vcf.gz (40.7%)
VN	17444346	PA_TruseqNano_HGCTCDSXY.vcf.gz (44.0%)
VN	22219906	AA_TruseqNano_HGCTCDSXY.vcf.gz (59.3%)	PA_TruseqNano_HGCTCDSXY.vcf.gz (56.0%)
#SN Summary Numbers. Use `grep ^SN | cut -f 2-` to extract this part.
SN	Number of REF matches:	21920752
SN	Number of ALT matches:	20685737
SN	Number of REF mismatches:	299154
SN	Number of ALT mismatches:	1235015
SN	Number of samples in GT comparison:	0


vcf-compare AA_TruseqNano_HGCTCDSXY.vcf.gz PM_TruseqNano_HGCTCDSXY.vcf.gz

# This file was generated by vcf-compare.
# The command line was: vcf-compare(v0.1.14-12-gcdb80b8) AA_TruseqNano_HGCTCDSXY.vcf.gz PM_TruseqNano_HGCTCDSXY.vcf.gz
#
#VN 'Venn-Diagram Numbers'. Use `grep ^VN | cut -f 2-` to extract this part.
#VN The columns are:
#VN        1  .. number of sites unique to this particular combination of files
#VN        2- .. combination of files and space-separated number, a fraction of sites in the file
VN	13905393	AA_TruseqNano_HGCTCDSXY.vcf.gz (37.1%)
VN	18640961	PM_TruseqNano_HGCTCDSXY.vcf.gz (44.2%)
VN	23551354	AA_TruseqNano_HGCTCDSXY.vcf.gz (62.9%)	PM_TruseqNano_HGCTCDSXY.vcf.gz (55.8%)
#SN Summary Numbers. Use `grep ^SN | cut -f 2-` to extract this part.
SN	Number of REF matches:	23243586
SN	Number of ALT matches:	21956079
SN	Number of REF mismatches:	307768
SN	Number of ALT mismatches:	1287507
SN	Number of samples in GT comparison:	0


vcf-compare AA_TruseqNano_HGCTCDSXY.vcf.gz W_TruseqNano_HGCTCDSXY.vcf.gz

# The command line was: vcf-compare(v0.1.14-12-gcdb80b8) AA_TruseqNano_HGCTCDSXY.vcf.gz W_TruseqNano_HGCTCDSXY.vcf.gz
#
#VN 'Venn-Diagram Numbers'. Use `grep ^VN | cut -f 2-` to extract this part.
#VN The columns are:
#VN        1  .. number of sites unique to this particular combination of files
#VN        2- .. combination of files and space-separated number, a fraction of sites in the file
VN	14694012	AA_TruseqNano_HGCTCDSXY.vcf.gz (39.2%)
VN	18497919	W_TruseqNano_HGCTCDSXY.vcf.gz (44.8%)
VN	22762735	AA_TruseqNano_HGCTCDSXY.vcf.gz (60.8%)	W_TruseqNano_HGCTCDSXY.vcf.gz (55.2%)
#SN Summary Numbers. Use `grep ^SN | cut -f 2-` to extract this part.
SN	Number of REF matches:	22452911
SN	Number of ALT matches:	21176721
SN	Number of REF mismatches:	309824
SN	Number of ALT mismatches:	1276190
SN	Number of samples in GT comparison:	0



bcftools isec snp.vcf.gz snp.vcf.gz -p isec

s1=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/AA1/AA1_TruseqNano_HGCTCDSXY.vcf.gz
s2=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/AM1/AM1_TruseqNano_HGCTCDSXY.vcf.gz

vcf-compare $s1 $s2

VN 'Venn-Diagram Numbers'. Use `grep ^VN | cut -f 2-` to extract this part.
#VN The columns are:
#VN        1  .. number of sites unique to this particular combination of files
#VN        2- .. combination of files and space-separated number, a fraction of sites in the file
VN	9749308	/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/AA1/AA1_TruseqNano_HGCTCDSXY.vcf.gz (47.7%)
VN	10088366	/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/AM1/AM1_TruseqNano_HGCTCDSXY.vcf.gz (48.5%)
VN	10691449	/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/AA1/AA1_TruseqNano_HGCTCDSXY.vcf.gz (52.3%)
/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/AM1/AM1_TruseqNano_HGCTCDSXY.vcf.gz (51.5%)
#SN Summary Numbers. Use `grep ^SN | cut -f 2-` to extract this part.
SN	Number of REF matches:	10579232
SN	Number of ALT matches:	10199310
SN	Number of REF mismatches:	112217
SN	Number of ALT mismatches:	379922
SN	Number of samples in GT comparison:	0


bedtools jaccard -a $s1 -b $s2

intersection	union	jaccard	n_intersections
15434665	47455670	0.325244	10089394

number of SNPs: 31124581
number of SNPs: 33565297

bcftools isec AA_TruseqNano_HGCTCDSXY.vcf.gz AM_TruseqNano_HGCTCDSXY.vcf.gz -p isec





############################################################################################
bcftools isec AA_TruseqNano_HGCTCDSXY.vcf.gz AM_TruseqNano_HGCTCDSXY.vcf.gz -p AAvsAM
bcftools isec AA_TruseqNano_HGCTCDSXY.vcf.gz PA_TruseqNano_HGCTCDSXY.vcf.gz -p AAvsPA
bcftools isec AA_TruseqNano_HGCTCDSXY.vcf.gz PM_TruseqNano_HGCTCDSXY.vcf.gz -p AAvsPM
bcftools isec AA_TruseqNano_HGCTCDSXY.vcf.gz W_TruseqNano_HGCTCDSXY.vcf.gz -p AAvsW


bcftools isec AM_TruseqNano_HGCTCDSXY.vcf.gz PA_TruseqNano_HGCTCDSXY.vcf.gz -p AMvsPA
bcftools isec AM_TruseqNano_HGCTCDSXY.vcf.gz PM_TruseqNano_HGCTCDSXY.vcf.gz -p AMvsPM
bcftools isec AM_TruseqNano_HGCTCDSXY.vcf.gz W_TruseqNano_HGCTCDSXY.vcf.gz -p AMvsW


bcftools isec PA_TruseqNano_HGCTCDSXY.vcf.gz PM_TruseqNano_HGCTCDSXY.vcf.gz -p PAvsPM
bcftools isec PA_TruseqNano_HGCTCDSXY.vcf.gz W_TruseqNano_HGCTCDSXY.vcf.gz -p PAvsW

bcftools isec PM_TruseqNano_HGCTCDSXY.vcf.gz W_TruseqNano_HGCTCDSXY.vcf.gz -p PMvsW

bcftools stats 0000.vcf > 0000.summary.txt
bcftools stats 0001.vcf > 0001.summary.txt
bcftools stats 0002.vcf > 0002.summary.txt
bcftools stats 0003.vcf > 0003.summary.txt


########################################################################################
vcf-compare AA_TruseqNano_HGCTCDSXY.vcf.gz AM_TruseqNano_HGCTCDSXY.vcf.gz > AAvsAM_vcf-compare.txt
vcf-compare AA_TruseqNano_HGCTCDSXY.vcf.gz PA_TruseqNano_HGCTCDSXY.vcf.gz > AAvsPA_vcf-compare.txt
vcf-compare AA_TruseqNano_HGCTCDSXY.vcf.gz PM_TruseqNano_HGCTCDSXY.vcf.gz > AAvsPM_vcf-compare.txt
vcf-compare AA_TruseqNano_HGCTCDSXY.vcf.gz W_TruseqNano_HGCTCDSXY.vcf.gz > AAvsW_vcf-compare.txt


vcf-compare AM_TruseqNano_HGCTCDSXY.vcf.gz PA_TruseqNano_HGCTCDSXY.vcf.gz > AMvsPA_vcf-compare.txt
vcf-compare AM_TruseqNano_HGCTCDSXY.vcf.gz PM_TruseqNano_HGCTCDSXY.vcf.gz > AMvsPM_vcf-compare.txt
vcf-compare AM_TruseqNano_HGCTCDSXY.vcf.gz W_TruseqNano_HGCTCDSXY.vcf.gz > AMvsW_vcf-compare.txt


vcf-compare PA_TruseqNano_HGCTCDSXY.vcf.gz PM_TruseqNano_HGCTCDSXY.vcf.gz > PAvsPM_vcf-compare.txt
vcf-compare PA_TruseqNano_HGCTCDSXY.vcf.gz W_TruseqNano_HGCTCDSXY.vcf.gz > PAvsW_vcf-compare.txt


vcf-compare PM_TruseqNano_HGCTCDSXY.vcf.gz W_TruseqNano_HGCTCDSXY.vcf.gz > PMvsW_vcf-compare.txt


#################################################################################################
bedtools jaccard -a AA_TruseqNano_HGCTCDSXY.vcf.gz -b AM_TruseqNano_HGCTCDSXY.vcf.gz > AAvsAM_bedtools_jaccard.txt
bedtools jaccard -a AA_TruseqNano_HGCTCDSXY.vcf.gz -b PA_TruseqNano_HGCTCDSXY.vcf.gz > AAvsPA_bedtools_jaccard.txt
bedtools jaccard -a AA_TruseqNano_HGCTCDSXY.vcf.gz -b PM_TruseqNano_HGCTCDSXY.vcf.gz > AAvsPM_bedtools_jaccard.txt
bedtools jaccard -a AA_TruseqNano_HGCTCDSXY.vcf.gz -b W_TruseqNano_HGCTCDSXY.vcf.gz > AAvsW_bedtools_jaccard.txt


bedtools jaccard -a AM_TruseqNano_HGCTCDSXY.vcf.gz -b PA_TruseqNano_HGCTCDSXY.vcf.gz > AMvsPA_bedtools_jaccard.txt
bedtools jaccard -a AM_TruseqNano_HGCTCDSXY.vcf.gz -b PM_TruseqNano_HGCTCDSXY.vcf.gz > AMvsPM_bedtools_jaccard.txt
bedtools jaccard -a AM_TruseqNano_HGCTCDSXY.vcf.gz -b W_TruseqNano_HGCTCDSXY.vcf.gz > AMvsW_bedtools_jaccard.txt


bedtools jaccard -a PA_TruseqNano_HGCTCDSXY.vcf.gz -b PM_TruseqNano_HGCTCDSXY.vcf.gz > PAvsPM_bedtools_jaccard.txt
bedtools jaccard -a PA_TruseqNano_HGCTCDSXY.vcf.gz -b W_TruseqNano_HGCTCDSXY.vcf.gz > PAvsW_bedtools_jaccard.txt


bedtools jaccard -a PM_TruseqNano_HGCTCDSXY.vcf.gz -b W_TruseqNano_HGCTCDSXY.vcf.gz > PMvsW_bedtools_jaccard.txt



###################################################################################################3
a=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/AA1/AA1_TruseqNano_HGCTCDSXY.vcf.gz
b=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/AA1R/AA1R_TruseqNano_HGCTCDSXY.vcf.gz
vcf-merge $a $b | bgzip -c > out.vcf.gz




a=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/AA1/AA1_TruseqNano_HGCTCDSXY.vcf.gz
b=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/AA1R/AA1R_TruseqNano_HGCTCDSXY.vcf.gz
c=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/AA3/AA3_TruseqNano_HGCTCDSXY.vcf.gz
d=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/AA5/AA5_TruseqNano_HGCTCDSXY.vcf.gz
e=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/AA5R/AA5R_TruseqNano_HGCTCDSXY.vcf.gz

vcf-merge $a $b $c $d $e | bgzip -c > AA_TruseqNano_HGCTCDSXY.vcf.gz



a=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/AM1/AM1_TruseqNano_HGCTCDSXY.vcf.gz
b=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/AM1R/AM1R_TruseqNano_HGCTCDSXY.vcf.gz
c=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/AM3R/AM3R_TruseqNano_HGCTCDSXY.vcf.gz
d=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/AM4R/AM4R_TruseqNano_HGCTCDSXY.vcf.gz
e=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/AM5R/AM5R_TruseqNano_HGCTCDSXY.vcf.gz

vcf-merge $a $b $c $d $e | bgzip -c > AM_TruseqNano_HGCTCDSXY.vcf.gz




a=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/PA1/PA1_TruseqNano_HGCTCDSXY.vcf.gz
b=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/PA2R/PA2R_TruseqNano_HGCTCDSXY.vcf.gz
c=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/PA3R/PA3R_TruseqNano_HGCTCDSXY.vcf.gz
d=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/PA4R/PA4R_TruseqNano_HGCTCDSXY.vcf.gz
e=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/PA5R/PA5R_TruseqNano_HGCTCDSXY.vcf.gz

vcf-merge $a $b $c $d $e | bgzip -c > PA_TruseqNano_HGCTCDSXY.vcf.gz


a=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/PM1R/PM1R_TruseqNano_HGCTCDSXY.vcf.gz
b=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/PM2R/PM2R_TruseqNano_HGCTCDSXY.vcf.gz
c=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/PM3R/PM3R_TruseqNano_HGCTCDSXY.vcf.gz
d=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/PM4/PM4_TruseqNano_HGCTCDSXY.vcf.gz
e=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/PM4R/PM4R_TruseqNano_HGCTCDSXY.vcf.gz

vcf-merge $a $b $c $d $e | bgzip -c > PM_TruseqNano_HGCTCDSXY.vcf.gz


a=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/W1R/W1R_TruseqNano_HGCTCDSXY.vcf.gz
b=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/W2/W2_TruseqNano_HGCTCDSXY.vcf.gz
c=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/W3/W3_TruseqNano_HGCTCDSXY.vcf.gz
d=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/W4R/W4R_TruseqNano_HGCTCDSXY.vcf.gz
e=/data/sata_data/workshop/wsu28/mosquito/mosquitoRG/rawMosquitoData/DRAGEN/processedData/OnlyVCF/W5/W5_TruseqNano_HGCTCDSXY.vcf.gz

vcf-merge $a $b $c $d $e | bgzip -c > W_TruseqNano_HGCTCDSXY.vcf.gz


###########################################################################################
# Creating index

tabix -p vcf AA_TruseqNano_HGCTCDSXY.vcf.gz
tabix -p vcf AM_TruseqNano_HGCTCDSXY.vcf.gz
tabix -p vcf PA_TruseqNano_HGCTCDSXY.vcf.gz
tabix -p vcf PM_TruseqNano_HGCTCDSXY.vcf.gz
tabix -p vcf W_TruseqNano_HGCTCDSXY.vcf.gz
